# Deterministic network-mesh generator for the STOOGE login background.
# Jittered grid of nodes, links between near neighbours.
# The beacon rings and sweep are CSS, in the stylesheet.
BEGIN {
    W = 1600; H = 900;
    COLS = 9; ROWS = 6;
    BX = 250; BY = 780;          # beacon origin
    THRESH = 265;                 # max link length

    n = 0;
    for (r = 0; r < ROWS; r++) {
        for (c = 0; c < COLS; c++) {
            # deterministic jitter: a cheap integer hash, no rand() so the
            # artwork is identical on every regeneration
            h1 = ((r * 73 + c * 151) * 2654435761) % 1000;
            h2 = ((r * 199 + c * 37) * 40503) % 1000;
            if (h1 < 0) h1 = -h1; if (h2 < 0) h2 = -h2;
            x = (c + 0.5) * (W / COLS) + (h1 / 1000.0 - 0.5) * 120;
            y = (r + 0.5) * (H / ROWS) + (h2 / 1000.0 - 0.5) * 100;
            n++;
            NX[n] = x; NY[n] = y;
            # every fifth node is a hub, drawn larger with a ring
            HUB[n] = ((r * COLS + c) % 5 == 0) ? 1 : 0;
        }
    }

    printf "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 %d %d\" width=\"%d\" height=\"%d\" fill=\"none\">\n", W, H, W, H;
    printf "  <!-- STOOGE login background: monitored-network mesh.\n";
    printf "       One mid-slate tone so the same file reads on a light or a dark\n";
    printf "       ground; the stylesheet varies only the opacity. Generated by\n";
    printf "       gen-topology.awk, deterministic (no rand). -->\n";
    printf "  <g stroke=\"#7f93aa\" stroke-width=\"1\">\n";

    # links
    for (i = 1; i <= n; i++) {
        for (j = i + 1; j <= n; j++) {
            dx = NX[i] - NX[j]; dy = NY[i] - NY[j];
            d = sqrt(dx * dx + dy * dy);
            if (d < THRESH) {
                o = 0.40 - (d / THRESH) * 0.24;
                printf "    <line x1=\"%.1f\" y1=\"%.1f\" x2=\"%.1f\" y2=\"%.1f\" opacity=\"%.2f\"/>\n", NX[i], NY[i], NX[j], NY[j], o;
            }
        }
    }
    printf "  </g>\n";

    # the beacon rings live in CSS instead, anchored to the same point as the
    # rotating sweep so the two stay aligned at any viewport aspect ratio

    # nodes last so they sit over the links
    printf "  <g fill=\"#7f93aa\">\n";
    for (i = 1; i <= n; i++) {
        if (HUB[i]) {
            printf "    <circle cx=\"%.1f\" cy=\"%.1f\" r=\"5.5\" opacity=\"0.70\"/>\n", NX[i], NY[i];
            printf "    <circle cx=\"%.1f\" cy=\"%.1f\" r=\"13\" fill=\"none\" stroke=\"#d63a22\" stroke-width=\"1.2\" opacity=\"0.55\"/>\n", NX[i], NY[i];
        } else {
            printf "    <circle cx=\"%.1f\" cy=\"%.1f\" r=\"3\" opacity=\"0.55\"/>\n", NX[i], NY[i];
        }
    }
    printf "  </g>\n";
    printf "</svg>\n";
}
